<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = getenv("SITENAME");
$wgMetaNamespace = "Project";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";

$wgArticlePath = "/wiki/$1";

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv("SERVER_URL");

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
];

## UPO means: this is also a user preference option

## Email
$wgEnableEmail = true;
$wgEnableUserEmail = false; # UPO
$wgEmailAuthentication = true;
$wgEmailConfirmToEdit = true;

$wgSMTP = [
    'host'      => getenv("EMAIL_HOST"),
    'IDHost'    => getenv("EMAIL_IDHOST"),
    'localhost' => getenv("EMAIL_IDHOST"),
    'port'      => getenv("EMAIL_PORT"),
    'auth'      => true,
    'username'  => getenv("EMAIL_USERNAME"),
    'password'  => getenv("EMAIL_PASSWORD")
];

$wgEmergencyContact = getenv("EMAIL_ADDRESS");
$wgPasswordSender = getenv("EMAIL_ADDRESS");

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO

## Database settings
$wgDBtype = getenv("DB_TYPE");
$wgDBserver = getenv("DB_HOST");
$wgDBname = getenv("DB_DATABASE");
$wgDBuser =  getenv("DB_USER");
$wgDBpassword = getenv("DB_PASSWORD");

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = true;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en-gb";

# Time zone
$wgLocaltimezone = "Europe/London";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = getenv("SECRET_KEY");

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = getenv("UPGRADE_KEY");

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "Creative Commons Attribution-ShareAlike";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# End of automatically generated settings.
# Add more configuration options below.


# Skins
$wgDefaultSkin = "timeless";
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# Extensions
wfLoadExtensions( [
    'Cargo',
    'CategoryTree',
    'CharInsert',
    'Cite',
    'CiteThisPage',
    'CodeEditor',
    'CodeMirror',
    'CommonsMetadata',
    'CookieWarning',
    'Description2',
    'Disambiguator',
    'DiscussionTools',
    'DismissableSiteNotice',
    'Echo',
    'EditCountNeue',
    'EmbedVideo',
    'Gadgets',
    'InputBox',
    'Interwiki',
    'Linter',
    'LoginNotify',
    'Loops',
    'Maps',
    'Math',
    'MultimediaViewer',
    'OATHAuth',
    'PageImages',
    'ParserFunctions',
    'ParserPower',
    'PdfHandler',
    'Poem',
    'Popups',
    'PortableInfobox',
    'RandomSelection',
    'ReplaceText',
    'RSS',
    'Scribunto',
    'SecureLinkFixer',
    'SyntaxHighlight_GeSHi',
    'TemplateData',
    'TemplateSandbox',
    'TemplateStyles',
    'TemplateWizard',
    'TextExtracts',
    'Thanks',
    'Thumbro',
    'timeline',
    'TitleKey',
    'TwoColConflict',
    'Variables',
    'VariablesLua',
    'VisualEditor',
    'WikiEditor',
    'WikiSEO'
] );

## Extension configs
### Cargo
$wgCargoDBtype = getenv("CARGO_DB_TYPE");
$wgCargoDBserver = getenv("CARGO_DB_HOST");
$wgCargoDBname = getenv("CARGO_DB_DATABASE");
$wgCargoDBuser = getenv("CARGO_DB_USER");
$wgCargoDBpassword = getenv("CARGO_DB_PASSWORD");
$wgCargoStoreUseTemplateArgsFallback = false;
$wgCargoPageDataColumns[] = 'creationDate';
$wgCargoPageDataColumns[] = 'modificationDate';
$wgCargoPageDataColumns[] = 'creator';
$wgCargoPageDataColumns[] = 'lastEditor';
$wgCargoPageDataColumns[] = 'fullText';
$wgCargoPageDataColumns[] = 'categories';
$wgCargoPageDataColumns[] = 'numRevisions';
$wgCargoPageDataColumns[] = 'outgoingLinks';
$wgCargoPageDataColumns[] = 'isRedirect';
$wgCargoPageDataColumns[] = 'pageNameOrRedirect';
$wgCargoPageDataColumns[] = 'pageIDOrRedirect';
$wgCargoFileDataColumns[] = 'mediaType';
$wgCargoFileDataColumns[] = 'path';
$wgCargoFileDataColumns[] = 'lastUploadDate';
$wgCargoFileDataColumns[] = 'fullText';
$wgCargoFileDataColumns[] = 'numPages';
$wgCargoPDFToText = 'pdftotext';
$wgCargoPDFInfo = 'pdfinfo';
### Cite
$wgCiteBookReferencing = true;
### CodeEditor
$wgDefaultUserOptions['usebetatoolbar'] = 1;
### CookieWarning
$wgCookieWarningEnabled = true;
### Description2
$wgEnableMetaDescriptionFunctions = true;
### Disambiguator
$wgDisambiguatorNotifications = true;
### Linter
// Load Parsoid
wfLoadExtension(
    'Parsoid',
	"$IP/vendor/wikimedia/parsoid/extension.json"
);

$wgParsoidSettings = [
    'useSelser' => true,
    'linting' => true
];

$wgVisualEditorParsoidAutoConfig = false; // to make linting work

$wgVirtualRestConfig = [
	'paths' => [],
	'modules' => [
		'parsoid' => [
			'url' => $wgServer . $wgScriptPath . '/rest.php',
			'domain' => substr($wgServer, 8),
			'forwardCookies' => true,
			'restbaseCompat' => false,
			'timeout' => 30
		],
	],
	'global' => [
		'timeout' => 360,
		'forwardCookies' => false,
		'HTTPProxy' => null
	]
];
### Math
$wgMathValidModes = [ 'source', 'native', 'mathjax', 'latexml' ];
$wgDefaultUserOptions['math'] = 'native';
### PageImages
$wgPageImagesDenylist = [[
		'type' => 'db',
		'page' => 'MediaWiki:Pageimages-denylist',
		'db' => false,
	]];
$wgPageImagesExpandOpenSearchXml = true;
### ParserFunctions
$wgPFEnableStringFunctions = true;
### Scribunto
$wgScribuntoDefaultEngine = 'luasandbox';
### TemplateStyles
$wgTemplateStylesAllowedUrls = [
    "audio" => [
        "<^https:\/\/warwick-wiki\.containers\.uwcs\.co\.uk\/w\/images\/[^?#]*>"
    ],
    "image" => [
        "<^https:\/\/warwick-wiki\.containers\.uwcs\.co\.uk\/w\/images\/[^?#]*>"
    ],
    "svg" => [
        "<^https:\/\/warwick-wiki\.containers\.uwcs\.co\.uk\/w\/images\/[^?#]*\\.svg(?:[?#]|$)>"
    ],
    "font" => [],
    "namespace" => [
        "<.>"
    ],
];
### TextExtracts
$wgExtractsExtendOpenSearchXml = true;
### Timeline
$wgTimelineFontDirectory = "/usr/share/fonts/truetype/freefont";
### WikiSEO
$wgWikiSeoDisableLogoFallbackImage = true;
$wgWikiSeoDefaultLanguage = $wgLanguageCode;
$wgWikiSeoEnableAutoDescription = true;
$wgWikiSeoTryCleanAutoDescription = true;


# User group rights
$wgGroupPermissions["*"]["createaccount"] = false;
$wgGroupPermissions["*"]["edit"] = false;

$wgGroupPermissions['user']['oathauth-enable'] = true;
$wgGroupPermissions['user']['writeapi'] = true;

$wgGroupPermissions['sysop']['interwiki'] = true;


# Footer text
$wgHooks['SkinAddFooterLinks'][] = function ( Skin $skin, string $key, array &$footerlinks ) {
    if ( $key === 'info' ) {
        $footerlinks['tagline'] = $skin->msg( 'footer-tagline' )->parse();
    }
};


# File types
$wgFileExtensions[] = 'svg';
$wgFileExtensions[] = 'pdf';


## Thumbnail sizes
$wgUploadThumbnailRenderMap = ['150', '250', '300', '500'];
$wgDefaultUserOptions['thumbsize'] = 4;



$wgJobRunRate = 0;